services:
  mysql:
    image: mysql:8.0
    container_name: mysql-desafio-contatos
    restart: always
    env_file:
      - .env
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_dados:/var/lib/mysql

volumes:
  mysql_dados:
